config/routes.rb
Rails.application.routes.draw do
  # get 'games/new'
  # get 'games/score'

  get '/new', to: 'games#new', as: :new
  post '/score', to: 'games#score', as: :score
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController

  def new
    @letters = (0...10).map { ('A'..'Z').to_a[rand(26)] }
  end

  def score

    @text_input = params[:shot].upcase.split("")
    new_letters = params[:letters].gsub(/\s+/, "").split("")

    matching_letters = @text_input.select do |letter|
      new_letters.include?(letter)
    end

    unmatching_letters = @text_input.reject do |letter|
      new_letters.include?(letter)
    end

    filepath = "https://wagon-dictionary.herokuapp.com/#{params[:shot].upcase}"
    serialized_data = open(filepath).read
    data = JSON.parse(serialized_data)
    @word = data["word"]
    @length = data["length"]
    @time = Time.now - Time.parse(params[:time])

    if unmatching_letters.length != 0
      @result = "The letters did not match the grid!"
      @score = 0
    elsif data["found"] == false
      @result = "Your word matches the grid but is not in the dictionary"
      @score = 0
    else
      @result = "Match!"
      @score = data["length"] * 10 + (60 - @time).round()
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>

<ul class="list-inline">
  <% @letters.each do |letter| %>
    <li class="letter"><%= letter %></li>
  <% end %>
</ul>
<form action="<%= score_path %> " method="post">
  <%= hidden_field_tag :letters, @letters %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="time" value='<%= Time.now %>' >
  <!-- <input type="hidden" name="letters" value="<%= @letters %>"> -->
  <input type="text" name="shot">
  <input type="submit" value="Go!">
</form>

app/views/games/score.html.erb
<h1>Score</h1>

<p>What you got?</p>
<p><%= @result %></p>
<p>Your word: <%= @word %></p>
<p>Your word-length: <%= @length %> letters</p>
<p>Your time: <%= @time.round() %> seconds</p>
<h2>Your score: <%= @score %></h2>

<a href="./new">Play again</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>